version: 2.1

executors:
  exectr:
    docker:
      - image: radman/cppdockercontainer:latest
        auth:
          username: radman
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup googletest
          command: |
            cd third_party
            git submodule init
            git submodule update
      - run: 
          name: Configure the build
          command: |
            export PATH='/usr/local/bin:$PATH'
            mkdir build
            cmake . -DCMAKE_BUILD_TYPE=Debug -B build
      - run: 
          name: Build the code
          command: |
            export PATH='/usr/local/bin:$PATH'
            cd build
            make
      - persist_to_workspace:
          root: .
          paths: build
  
  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build
            make coverage
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build