version: 2.1

jobs:
  build:
    docker:
      - image: debian:stretch
        auth:
          username: radman  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: |
            apt-get update
            apt-get install -y sudo
            rm -rf /var/lib/apt/lists/*
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing PIP
          command: |
            python < (curl https://bootstrap.pypa.io/get-pip.py)
            python -m pip install -U pip
      - run:
          name: Installing CMAKE
          command: |
            sudo pip insatll cmake
      - run:
          name: Installing GTest
          command: |
            sudo apt install libgtest-dev
            cd /usr/src/googletest
            export PATH='/usr/local/bin:$PATH'
            sudo cmake .
            sudo cmake --build . --target install
      - run:
          name: Installing Code Coverage
          command: |
            #pip install setuptools
            pip install gcovr
      - run: 
          name: Configure the build
          command: |
            export PATH='/usr/local/bin:$PATH'
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug
      - run: 
          name: Build the code
          command: |
            export PATH='/usr/local/bin:$PATH'
            cd build
            make
      - run: 
          name: Run coverage
          command: |
            export PATH='/usr/local/bin:$PATH'
            cd build
            make coverage
            bash <(curl -s https://codecov.io/bash)