version: 2.1

jobs:
  build:
    docker:
      - image: debian:stretchauth:
          username: radman  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference
    steps:
      - checkout