version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  exectr:
    docker:
      - image: radman/cpp_dev_container:latest
        auth:
          username: radman
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup googletest
          command: |
            cd third_party
            git submodule init .
            git submodule update
      - run: 
          name: Configure the build
          command: |
            export PATH="/usr/local/bin:$PATH"
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug
            make
      - persist_to_workspace:
          root: ~/
          paths: 
            - project
            - project/build
  
  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Execute Tests
          command: |
            cd build
            make coverage
      - codecov/upload
          file: coverage.xml
      - store_test_results:
          path: build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build